yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions:
  '@aave/contract-helpers@*':
    dependencies:
      tslib: '*'
      '@ethersproject/contracts': '*'
      '@ethersproject/bytes': '*'
      'bignumber.js': '*'
